apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  {{#if ingress}}
  ingresses:
    - {{ingress}}
  {{/if}}
  liveness:
    path: /internal/health
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 800Mi
    requests:
      cpu: 100m
      memory: 650Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: spinnsyn-arkivering-db
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-frontend-arkivering
        - application: spinnsyn-backend
  kafka:
    pool: {{kafkaPool}}
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}

