db_tier: db-custom-1-3840
app: spinnsyn-arkivering
namespace: flex
team: flex
kafkaPool: nav-prod
azureTenant: nav.no
cpu: 100m
memory: 2048Mi
external-host:
  - dokarkiv.prod-fss-pub.nais.io
  - cdn.nav.no
env:
  SPINNSYN_FRONTEND_ARKIVERING_AAD_CLIENT_ID: prod-gcp.flex.spinnsyn-frontend-arkivering
  DOKARKIV_AAD_CLIENT_ID: prod-fss.teamdokumenthandtering.dokarkiv
  DOKARKIV_URL: https://dokarkiv.prod-fss-pub.nais.io
