db_tier: db-custom-1-3840
app: spinnsyn-arkivering
namespace: flex
team: flex
kafkaPool: nav-prod
azureTenant: nav.no
external-host:
  - dokarkiv.prod-fss-pub.nais.io
env:
  SPINNSYN_FRONTEND_ARKIVERING_AAD_CLIENT_ID: prod-gcp.flex.spinnsyn-frontend-arkivering
  SPINNSYN_BACKEND_AAD_CLIENT_ID: prod-gcp.flex.spinnsyn-backend
  DOKARKIV_AAD_CLIENT_ID: prod-fss.teamdokumenthandtering.dokarkiv
  DOKARKIV_URL: https://dokarkiv.prod-fss-pub.nais.io
